---
title: "Algebra lineal computacional"
---
## Descripción de la asignatura
En la actualidad los problemas que estudia la matemática aplicada tiene un gran componente computacional, esto requiere un buen entendimiento e interpretación adecuada de los diferentes algoritmos que se usan para resolver problemas. En especial los algoritmos donde se usan muchas variables y/o iterativos para tener una apropiada interpretación de los resultados y que estos reflejen la realidad de los mismos. Es por es este motivo que este curso pretende dar algunas competencias computacionales y analíticas para el estudio del álgebra matricial computacional. En este curso se presentan los algoritmos y la teoría para resolver sistemas de ecuaciones lineales, debido a que estas están presentes en casi toda aplicación de modelos matemáticos.

## Capitulo 1
-   Espacios con producto interno. 
-   Bases ortogonales en espacios vectoriales con producto interno.
-   Espacios de matrices. 
-   Espacios Normados en dimensión finita.
-   Desigualdad de Cauchy-Schwars.
-   Espacios $l_p$,  $L2(Cn[a, b])$. 
-   Normas de Matrices. 
-   Normas inducidas, norma de Frabenius, equivalencia de normas y calculo de normas. 
-   Equivalencia de normas.

## Capitulo 2
- Análisis de sensibilidad de sistemas de ecuaciones lineales. 
- Análisis del error. 
- Número de condición. 
- Perturbación de un sistema de ecuaciones. 
- Ejemplos con matrices un número de dimensión grande.

## Capitulo 3
- Métodos de solución de sistemas lineales. 
- Factorización LU. 
- Matrices definidas positivas y negativas. 
- Método directos, Cholesky, gradiente Conjugado, Algoritmos de Thomas. 
- Métodos iterativos (Jacobi, Gauss Saidel). Programación y ejemplos computacionales.

## Capitulo 4
- Proyección ortogonal. 
- Subespacios complementarios, descomposición ortogonal, teorema del rango y nulidad. 
- Factorización QR. 
- Algoritmos computacionales: procesos Gram-Schmidt.

## Capitulo 5
- Problema de mínimos cuadrados 
- Rango completo, rango deficiente. 
- Cuadrado mínimo con restricciones. 
- Problema de punto de silla. 
- Método de Uzawa. 
- Método de ecuaciones normales, inversa generalizada. 
- Soluciones numéricas, Cholesky, gradiente conjugado. 
- Problemas de aplicación.

## Capitulo 6
- Descomposición en valores singulares, Aplicaciones de la Descomposición en valores singulares, Solución de ecuaciones normales. 
- Aplicación compresión de imágenes. 
- Descomposición de Shur, Teorema espectral.

## Capitulo 7
- Autovalores de una matriz. 
- Teorema de los círculos de Gershgorin Algoritmo QR (soluciones reales). 
- Método de las potencias.

## Bibiolografías
- Meyer, c. d. (2000). matrix analysis and applied linear algebra (vol. 2). 
- Siam. pulino, p. (2012). algebra linear e suas aplicaccoes: notas de aula. 
- Trefethen, l. n., & bau iii, d. (1997). Numerical linear algebra (vol. 50). 
- Siam.|demmel, j. w. (1997). applied numerical linear algebra. society for industrial and applied mathematics.
