---
title: "Introducción a la modelización"
---
## Descripción de la materia
Introducción a la modelización es una asignatura de primer semestre de la carrera de matemáticas aplicadas, en ella se busca motivar a los estudiantes para que realicen una simplificación de algún fenómeno real, identificando las principales variables y las relaciones entre ellas Con este propósito la asignatura se ha divido en tres partes. En la primer parte se da una muy breve introducción a las ecuaciones en diferencias y sistemas dinámicos de ecuaciones en diferencias. En la segunda se presentan algunos modelos en donde sus variables están proporcionalmente relaciones, también se hacen ajustes polinomiales para los datos de un experimento. En la última parte se presenta la teoría de grafos como una herramienta descriptiva para dar una interpretación de algunos fenómenos concretos del mundo real.

## Primera parte:
- Modelando el cambio
- Ecuaciones en diferencias
- Solución a sistemas dinámico
- Sistemas de diferencias.

## Segunda parte:
- Modelos matemáticos: 
    - Modelos usando proporcionalidad
    - Modelos usando similaridad geométrica
    - Ajustar gráficamente modelos a datos
- Métodos analíticos para ajustar datos, Aplicando el criterio de mínimos cuadrados.

## Tercer parte:
- Introducción a la modelizacion experimental
- Grafos como modelos:
    - Describiendo grafos
    - Modelos con grafos
    - Usando modelos de grafos para solucionar problemas

