---
title: "Modelización y simulación I"
---

## Descripción de la materia
La modelización matemática es un rama principal en las matemáticas aplicadas, este curso va dirigido a estudiantes de matemática aplicada e ingeniera y pretende dar las principales herramientas para modelizar problemas donde involucren razones de cambio. Adicionalmente, pretendemos presentar algunas herramientas numéricas, basadas en diferencias finitas, para aproximar estos sistemas, mostrando algunos principios de estabilidad. De esta manera deseamos que es estudiante adquiera la habilidad de esquematizar un problema real en un sistema de ecuaciones diferenciales ordinarias, para que posteriormente simule e interprete las aproximaciones en un contexto dado. Adquiriendo asÍ, las capacidades simular problemas reales en diferentes contextos de las ciencias y adquirir la competencia de trabajar en equipos interdisciplinares, convirtiendo las matemática aplicadas como un laboratorio del mundo real.

## Capitulo 1 
-   Introducción al modelización.
-   ¿Qué es modelización matemática? 
-   Principios de conservación y balance.
-   Análisis dimensional. 
-   Escaling.

## Capitulo 2 
-   Modelos continuos.
-   Ejemplos de modelos en ecuaciones diferenciales ordinarias:
    -   Modelos de crecimiento exponencial (crecimiento radiactivo, crecimiento de bacterias).
    -   Modelo logístico (modelos con capacidad de carga). 
    -   Modelos de competencia de especies (depredador presa).
    -   Modelos de cooperación. Modelos en equilibrio.
    -   Modelos amortiguados.

## Capitulo 3 
-   Simulación numérica.
-   Diferencias finitas.
-   Aproximaciones de 1, 2 y alto orden. 
-   Error local y error global.
-   Problemas de valor inicial en ecuaciones diferenciales ordinarias.
-   Relación entre la teoría de EDO y aproximaciones numéricas(existencia y unicidad, funciones lipchitz continuas).

## Capitulo 4 
-   Métodos de un solo paso.
-   Método de Euler explicito e implícito. 
-   Métodos en series de Taylor.
-   Métodos Runge-Kuta. 
-   Métodos lineales multipaso
-   Familias Adams-Bashforth, Adams-Boulton y Predictor-corrector
-   Programación numérica de los métodos para PVI. 

## Capitulo 5 
-   Cero estabilidad en métodos de un solo paso. 
-   Zero estabilidad en métodos multipaso. 
-   Absoluta estabilidad:
    -   Regiones de absoluta estabilidad. 

## Capitulo 6 
-   Ecuaciones diferenciales tipo stiff. 
-   Dificultades numéricas asociadas. 
-   Métodos numéricos A-estabilidad y L-estabilidad. 

## Capitulo 7 
-   Simulación de sistemas de ecuaciones diferenciales. 
-   Métodos de un solo paso.
-   Métodos multipaso (implícitos-explícitos). 
-   Simulación en problemas reales.