---
title: "Servicios"
---
Estos son los programas y lenguajes que estarán disponibles en el laboratorio:

## Lenguajes de programación
- Python
- R
- Quarto
- Julia

## Entornos
- Anaconda
- Spyder
- Jupyter
- Visual Studio Code

Dejamos algunos cursos de programación gratis en algunos de los lenguajes de programación:

## Cursos de programación para Python
Página oficial de Python: [python.org](https://www.python.org/)

- Curso en español de Codecademy: [codecademy.com/learn/learn-python](https://www.codecademy.com/learn/learn-python)
- Curso de para principiantes en Coursera: [coursera.org/learn/python](https://www.coursera.org/learn/python)
- Curso de Google para principiantes: [developers.google.com/edu/python](https://developers.google.com/edu/python?hl=es-419)

Cursos de las librerías mas utilizadas en Python:

- Curso de NumPy de DataCamp: [datacamp.com/courses/intro-to-python-for-data-science](https://www.datacamp.com/courses/intro-to-python-for-data-science)
- Curso de NumPy y Pandas en español de Platzi: [platzi.com/cursos/data-python/](https://platzi.com/cursos/data-python/)
- Curso de Matplotlib en español de Coursera: [coursera.org/learn/python-plotting](https://www.coursera.org/learn/python-plotting)

## Cursos de programación para R
Pagina oficial de R: [rstudio.com](https://www.rstudio.com/)

- Curso en español de Coursera: [coursera.org/learn/r-programming](https://www.coursera.org/learn/r-programming)
- Curso básico de DataCamp: [datacamp.com/courses/free-introduction-to-r](https://www.datacamp.com/courses/free-introduction-to-r)

## Cursos de programación para Julia
Pagina oficial de Julia: [julialang.org](https://julialang.org/)

- Curso Introducción en DataCamp: [datacamp.com/courses/introduction-to-julia](https://www.datacamp.com/courses/introduction-to-julia)
- Curso de Codecademy: [codecademy.com/learn/learn-julia](https://www.codecademy.com/learn/learn-julia)

## Cursos para Quarto
Página oficial de Quarto: [quarto.org](https://quarto.org/)